# Generated by Django 5.0.7 on 2024-08-04 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creationData',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner_id', models.CharField(default=None)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
    ]
