# Generated by Django 5.0.8 on 2024-08-17 14:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Bid", "0002_remove_creationdata_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="creationdata",
            name="mage",
            field=cloudinary.models.CloudinaryField(
                default=1, max_length=255, verbose_name="image"
            ),
            preserve_default=False,
        ),
    ]
