# Generated by Django 5.0.8 on 2024-08-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bid", "0003_creationdata_mage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="creationdata",
            old_name="mage",
            new_name="image",
        ),
        migrations.AddField(
            model_name="creationdata",
            name="name",
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
