# Generated by Django 5.0.8 on 2024-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bid", "0005_alter_creationdata_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creationdata",
            name="owner_id",
            field=models.CharField(default=""),
        ),
    ]
