# Generated by Django 5.0.8 on 2024-08-19 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bid", "0006_alter_creationdata_owner_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuyModel",
            fields=[
                (
                    "order_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("owner_id", models.CharField(default="")),
                ("bider_id", models.CharField(default="")),
                ("original_price", models.FloatField(default=0.0)),
                ("updated_price", models.FloatField(default=0.0)),
            ],
        ),
    ]
