# Generated by Django 5.0.8 on 2024-08-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bid", "0008_buymodel_iswishlisted"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotifyAndWishlistModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_id", models.CharField(default="")),
                ("bider_id", models.CharField(default="")),
                ("isWishlisted", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="buymodel",
            name="isWishlisted",
        ),
    ]
