# Generated by Django 5.0.8 on 2024-08-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bid", "0009_notifyandwishlistmodel_remove_buymodel_iswishlisted"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifyandwishlistmodel",
            name="product_id",
            field=models.CharField(default=""),
        ),
    ]
