# Generated by Django 5.0.8 on 2024-08-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bid", "0010_notifyandwishlistmodel_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="buymodel",
            name="product_id",
            field=models.CharField(default=""),
        ),
    ]
