# Generated by Django 5.0.8 on 2024-08-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bid", "0011_buymodel_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="buymodel",
            name="updatedByOwner",
            field=models.BooleanField(default=False),
        ),
    ]
